[package]
name = "rusqlite_orm"
version = "0.5.2"
edition = "2024"
description = "ORM for rusqlite"
repository = "https://github.com/Emiliopg91/rusqlite_orm/orm"
readme = "README.md"
license = "MIT"
categories = ["database"]

[dependencies]
r2d2 = "0"
r2d2_sqlite = { version = "0", features = ["bundled"] }
thiserror = "2"
log = "0"
serde = "1.0.229"
rusqlite_orm_macros = { version = "0.5", path = "../macros", optional = true }

[features]
derive = ["dep:rusqlite_orm_macros"]

[dev-dependencies]
tempfile = "^3"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
